version: '3'
services:
  redis:
    container_name: redis-container
    image: redis
    ports:
      - "6379:6379"
  publisher:
    container_name: publisher-container
    build: ./publisher
    restart: always
    image: node-publisher
    ports:
      - "8080:8080"
    links:
      - redis
  subscriber:
    container_name: subscriber-container
    build: ./subscriber
    restart: always
    image: node-subscriber
    ports:
      - "8081:8081"
    links:
      - redis
